// Copyright (c) 2025 Huawei Device Co., Ltd. All rights reserved
// Use of this source code is governed by a Apache-2.0 license that can be
// found in the LICENSE file.

import {RNCWebView as WebView} from './src/main/ets/RNCWebView'
import {RNCWebViewPackage as WebViewPackage} from './src/main/ets/RNCWebViewPackage'

export {WebViewPackage};
export { WebView }

export * from './src/main/ets/RNCWebView'

export * from './ts'